### ISSUE TITLE
Issue with NSHomeDirectory

### ISSUE THREAD

**Issue by malhal** [Siguza/psychicpaper#3]
Firstly thanks so much for sharing this, I am certainly having fun!

Despite being a `no-container` and `platform-application` app, the file APIs `NSHomeDirectory()`, `URLsForDirectory`, `NSSearchPathForDirectoriesInDomains` etc. are all still returning the data container (and its not writeable) rather than the `/var/mobile` I was expecting. I'm not sure but it could be because the app is launched from a container path. Are you aware of any way to fix that? 

FYI NSUserDefaults is already correctly saving its plist to `/var/mobile`

**Comment by Siguza** [comment]
Is this enough for your needs?:

```c
setenv("CFFIXED_USER_HOME", "/var/mobile", 1);
```

**Comment by malhal** [comment]
This is great thanks, I wasn't aware the container is implemented using environment variables, I adjusted my main with the extra param to have a look at them:

```
int main(int argc, char * argv[], char **envp) {
    NSString * appDelegateClassName;
    @autoreleasepool {
        for (char **env = envp; *env != 0; env++)
        {
          char *thisEnv = *env;
          printf("%s\n", thisEnv);
        }
        appDelegateClassName = NSStringFromClass([AppDelegate class]);
    }
    return UIApplicationMain(argc, argv, nil, appDelegateClassName);
}
```

This is what iOS 13.4.1 on iPhone XR outputs including the `CFFIXED_USER_HOME`:
```
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
CA_ASSERT_MAIN_THREAD_TRANSACTIONS=0
USER=mobile
METAL_DEVICE_WRAPPER_TYPE=1
LOGNAME=mobile
PATH=/usr/bin:/bin:/usr/sbin:/sbin
NSUnbufferedIO=YES
CFFIXED_USER_HOME=/private/var/mobile/Containers/Data/Application/73F23E54-C7B6-45AF-9210-899790399A43
METAL_DEBUG_ERROR_MODE=0
GPUProfilerEnabled=YES
SWIFTUI_VIEW_DEBUG=287
HOME=/private/var/mobile/Containers/Data/Application/73F23E54-C7B6-45AF-9210-899790399A43
OS_ACTIVITY_DT_MODE=YES
SQLITE_ENABLE_THREAD_ASSERTIONS=1
SHELL=/bin/sh
__CF_USER_TEXT_ENCODING=0x1F5:0:0
CLASSIC_OVERRIDE=0
TMPDIR=/private/var/mobile/Containers/Data/Application/73F23E54-C7B6-45AF-9210-899790399A43/tmp
CA_DEBUG_TRANSACTIONS=0
XPC_SERVICE_NAME=UIKitApplication:com.malhal.PsychicWiFi[1179][rb-legacy]
XPC_FLAGS=0x0
```

I went with `unsetenv("CFFIXED_USER_HOME");` before I call UIApplicationMain and then the `NSHomeDirectory` methods become the expected `/var/mobile` and solved my issue thanks.

Fyi interesting to look at how `CFFIXED_USER_HOME` is used in [CFPlatform.c](https://opensource.apple.com/source/CF/CF-855.17/CFPlatform.c)

**Comment by Siguza** [comment]
Alright, gonna mark this as fixed then.
