### ISSUE TITLE
Entitlements not applying

### ISSUE THREAD

**Issue by jasperswallen** [Siguza/psychicpaper#4]
I'm not 100% sure if I'm doing something wrong here or it just doesn't work, but I can't seem to duplicate this bug on my iPhone XR (iOS 13.3, jailbroken).

Creating a new app with [this](https://wojciechregula.blog/post/stealing-your-sms-messages-with-ios-0day/) tutorial simply sends "Nope" (since /private/var/... is not readable) even with a properly codesigned (afaik) app. (I also tried doing this on my own app previously with other entitlements and it didn't work, this was just to verify that it doesn't work). I have tried signing with `codesign -d --entitlements [path].app [entitlements file] -f -s "[dev profile]"` and then installing with ios-deploy (or from Xcode). I also tried using [this gist](https://gist.github.com/ChiChou/9017580d4adb60d7e43fb9535a8a0273). I seems like the apps are correctly being signed with the comments, but the entitlements are not being applied.

To see if the apps are actually signed with the entitlements, I ran `jtool2` on them:
<img width="862" alt="Screen Shot 2020-05-08 at 11 38 03 PM" src="https://user-images.githubusercontent.com/44964970/81464219-2e331900-9185-11ea-8e9e-23e20d135b29.png">

This implied that the codesigning succeeded. However, in the `embedded.mobileprovision`, these entitlements *do not* exist (although strangely, the wireless configuration entitlement does). 
<img width="736" alt="Screen Shot 2020-05-08 at 11 40 11 PM" src="https://user-images.githubusercontent.com/44964970/81464237-62a6d500-9185-11ea-9c51-eab0c4581ddc.png">

**Comment by Siguza** [comment]
Definitely weird. As a first step, could you call `csops()` from within your app to get the parsed entitlements blob and see if it made it into the device?

Basically this:

```
extern int csops(pid_t pid, unsigned int  ops, void * useraddr, size_t usersize);

// in some func
{
    struct
    {
        uint32_t hdr[3];
        char ent[0x1000];
    } buf;
    int r = csops(getpid(), 7, &buf, sizeof(buf));
    NSLog(@"%d, %s", r, buf.ent);
}
```

That should dump the raw entitlements blob into syslog.

**Comment by jasperswallen** [comment]
Running that gives me this output:
<img width="859" alt="Screen Shot 2020-05-09 at 12 46 24 AM" src="https://user-images.githubusercontent.com/44964970/81465289-a6520c80-918e-11ea-810b-d4590c88d08c.png">

It seems like platform-application got copied but none of the rest. The `jtool2` and `embedded.mobileprovision` results are exactly the same, though.

**Comment by Siguza** [comment]
Oooooh wait. This is the jailbreak!  
It's injecting `platform-application` and `com.apple.private.skip-library-validation` in the csblob in kernel memory, and well... it looks like it uses CoreFoundation to parse entitlements there. :|

Yeah I don't have a fix for that. Best I can recommend is to reboot into unjailbroken state. :/

**Comment by jasperswallen** [comment]
Hmm, interesting. That fixed the injection issue but (and this is probably unrelated) some entitlements don't seem to get applied. The `com.apple.private.security.storage.Messages` entitlement works fine (I'm able to dump sms.db now), but `com.apple.developer.payment-pass-provisioning` doesn't:
<img width="1143" alt="Screen Shot 2020-05-09 at 1 27 59 AM" src="https://user-images.githubusercontent.com/44964970/81466118-ab19bf00-9194-11ea-998e-b2d8708c748b.png">

`com.apple.developer.associated-domains` also doesn't seem to work:
`2020-05-09 01:32:46.008630-0500 appname[390:15962] [AutoFill] Cannot show Automatic Strong Passwords for app bundleID: com.[appname] due to error: Cannot save passwords for this app. Make sure you have set up Associated Domains for your app and AutoFill Passwords is enabled in Settings`

**Comment by Siguza** [comment]
If the daemon uses CoreFoundation to parse entitlements, then it won't see the rogue ones. In my original write-up I suggested spawning entitled binaries and using task ports to make them do our bidding. It turns out this doesn't work off the bat anymore, but I just published a workaround that should work almost as well:

https://github.com/Siguza/psychicpaper/blob/master/stuff/proxy.m
