### ISSUE TITLE
socket AF_SYSTEM entitlement?

### ISSUE THREAD

**Issue by malhal** [Siguza/psychicpaper#6]
Hi my app requires opening a socket with AF_SYSTEM which I can achieve with `platfom-application` and `...-no-container` in my psychic paper, however given these have other side-effects I thought I'd ask if you know of a more specific entitlement for this? Before console logs went private it was the one that outputs "'deny system socket".

**Comment by Siguza** [comment]
I'm afraid I don't.  
And after looking at sandbox profiles for a bit, it seems there isn't a special entitlement for it, but it's rather just a property of the sandbox profile you have applied...

**Comment by gabriel-1988** [comment]
Df

**Comment by gabriel-1988** [comment]
Y
